### ISSUE TITLE
Readme of the Library

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios-inventory#3]
Write the README.md with a similar format of this one:
https://github.com/emqtt/CocoaMQTT

**Comment by hectorerb** [comment]
UIDevice is a class that provides access to some properties of the current device
https://developer.apple.com/documentation/uikit/uidevice

**Comment by ajsb85** [comment]
Badge for Travis CI
https://travis-ci.org/flyve-mdm/flyve-mdm-ios-inventory.svg?branch=master

**Comment by ajsb85** [comment]
Repo Status Badge

[![Project Status: WIP – Initial development is in progress, but there has not yet been a stable, usable release suitable for the public.](http://www.repostatus.org/badges/latest/wip.svg)](http://www.repostatus.org/#wip)

**Comment by ajsb85** [comment]
Banner
![github-banner](https://user-images.githubusercontent.com/663460/26935464-54267e9c-4c6c-11e7-86df-8cfa6658133e.png)

**Comment by ajsb85** [comment]
We need to update information about the Cocoapod URL and review the entire README.
I will help you with that.
