### ISSUE TITLE
Automated CocoaPod releases with Travis CI

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/flyve-mdm-ios-inventory#34]
Documentation
https://fuller.li/posts/automated-cocoapods-releases-with-ci/

**Comment by ajsb85** [comment]
Duplicate: https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/10

**Comment by ajsb85** [comment]
I will move your reserch @hectorerb to the proper issue #10
