### ISSUE TITLE
Create project page

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-ios-inventory#50]
Hi, @ajsb85

I will create gh-pages as requested in this issue: flyve-mdm/flyve-mdm.github.io#13

Regards.

**Comment by ajsb85** [comment]
Task related https://github.com/flyve-mdm/flyve-mdm-press-kit/issues/28
To finish this issue. 👍

**Comment by ajsb85** [comment]
The project site is here at the moment: http://flyve.org/flyve-mdm-ios-inventory/
