### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-ios-inventory#52]
The secciontion of "What's included?" **Is outdated**. 
It is necessary to place only real information

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

You will work on that or to request to Hector?

**Comment by ajsb85** [comment]
This is the branch to improve the readme:

https://github.com/flyve-mdm/flyve-mdm-ios-inventory/tree/feature/readme
