### ISSUE TITLE
Generate package app

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-ios-inventory#55]
Hi, @hectorerb 

It is necessary to package the application for demos. This will be used in the next section:

![flyve-mdm github io-flyve-mdm-ios-inventory-](https://user-images.githubusercontent.com/19965590/29571252-ba9b71ba-8726-11e7-8a7e-60e8b0fd03ac.png)

Thanks.

**Comment by ajsb85** [comment]
Hi, @hectorerb 

Could you pack (tar.gz or zip) with CircleCI the example folder to upload as artifact into the github release?

Thanks.

**Comment by hectorerb** [comment]
@ajsb85 Do you suggest any name or location for pack?

**Comment by hectorerb** [comment]
@ajsb85 would be ideal to use conventional-github-releaser, but it still does not work
