### ISSUE TITLE
Quality Control

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-ios-inventory#9]
- [x] Swift Style Guide
- [ ] Check if the Podspec lints correctly.
This can be done with two methods, `pod lib lint` and `pod spec lint`. 
- [x] Unit Testing
- [ ] Integrate Travis CI for these tests

**Comment by hectorerb** [comment]
We use this swift style guide

https://github.com/raywenderlich/swift-style-guide

**Comment by ajsb85** [comment]
SwiftLint
https://github.com/realm/SwiftLint
